name: Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux with GCC
          - name: "Linux GCC"
            compiler: gcc
            cmake-generator: 'Ninja'
            cmake-options: '-DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++'
          
          # Linux with Clang
          - name: "Linux Clang"
            compiler: clang
            cmake-generator: 'Ninja'
            cmake-options: '-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build libasound2-dev libpulse-dev libpipewire-0.3-dev
      shell: bash

    - name: Configure CMake
      run: |
        cmake -B build -G "${{ matrix.cmake-generator }}" ${{ matrix.cmake-options }}

    - name: Build
      run: |
        cmake --build build --config Release

    - name: Build Debug (for better test debugging)
      run: |
        cmake -B build-debug -G "${{ matrix.cmake-generator }}" ${{ matrix.cmake-options }} -DCMAKE_BUILD_TYPE=Debug
        cmake --build build-debug --config Debug

    - name: Run tests (Release)
      working-directory: build
      run: |
        ./tests/soundcoe_tests
      shell: bash

    - name: Run tests (Debug)
      working-directory: build-debug
      run: |
        ./tests/soundcoe_tests
      shell: bash